name: BurcuAvci
favicon: null
layout_spectrum: 0.4500673529691994
typography_spectrum: 0.762649814831093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6949550886638463
  lightness: 0.09141064179129899
  saturation: 0.1358392173424363
  rhythmicContrast: 0.10748790763318539
purpose: []
